### ISSUE TITLE
How to prepare data as AlexeyAB/darknet's instructions?

### ISSUE THREAD

**Issue by lh641446825** [sjtuytc/betapose#4]
Please tell me how to prepare data as AlexeyAB/darknet's instructions? I download the darknet'code, but the "README.md" in `./scripts` folder just some website of dataset. I don't know how to prepare data as AlexeyAB/darknet's instructions.

**Comment by sjtuytc** [comment]
Basically, you only need to place the bounding boxes and original images to two folders. The tricky thing is our rendered dataset is too large to release. So you might render some one for yourself.

**Comment by lh641446825** [comment]
> Basically, you only need to place the bounding boxes and original images to two folders. The tricky thing is our rendered dataset is too large to release. So you might render some one for yourself.

The bounding boxes and original images are in two folders，the path is `./3_6Dpose_estimator/train_YOLO/data01`，one name is bbox，the other is rgb. They all from step 'Ⅲ. Annotate Keypoints'. I just want to know what should I do next? I only do

>  Build Darknet (YOLOv3).
> $ make
![image](https://github.com/lh641446825/picture/blob/master/1.png)
and don't know how to do next, it confused me.

**Comment by danieldimit** [comment]
As far as I know the @sjtuytc has just copied the code of YOLOv3. So to build it just follow the instructions from here [darknet](https://github.com/AlexeyAB/darknet). Then to train it follow the instructions also from [darknet](https://github.com/AlexeyAB/darknet). It is well documented. The problem is I did the thing I just described for the Ape object, but YOLOv3 didn't detect anything, so I guess I've done something wrong. Also the training takes very long time 6000 Iterations took ~60 hours of training.

@sjtuytc do you have any suggestions what I could have done wrong? And could you provide the weights that you've got for the LINEMODE dataset objects?

**Comment by sjtuytc** [comment]
Do you render a synthetic dataset as recommended? If you use a photo-realistic dataset, then detection will not be a big issue.
If not, you could also follow the split setting which means you split the LineMod in to training and test folds. You'll easily get very good detection results.

**Comment by lh641446825** [comment]
> 据我所知，@ sjtuytc刚刚复制了YOLOv3的代码。所以要建立它只需按照这里[暗网](https://github.com/AlexeyAB/darknet)的说明。然后按照[暗网](https://github.com/AlexeyAB/darknet)的说明进行训练。这是有据可查的。问题是我做了我刚刚为Ape对象描述的事情，但是YOLOv3没有检测到任何东西，所以我猜我做错了什么。此外，培训需要很长时间6000次迭代需要约60小时的培训。
> 
> @sjtuytc你有什么建议我可以做错了吗？你能提供你为LINEMODE数据集对象获得的权重吗？

@danieldimit @sjtuytcThe three tip , "README.md" in ./scripts folder just some website of dataset. I only need to downloaded pretrained darknet53 folder, then  compile yolo and train it? What documents do I need to replace? When you compile,  could you provide the parameters that you've set in the `Makefile`?

**Comment by lh641446825** [comment]
Thanks. When I run train_single.sh and train_all.sh,  I got the following information:

> Couldn't open file: data_linemod_gt/02/bvise.data
> Couldn't open file: data_linemod_gt/all/all.data

I didn't find the '.data' files. @sjtuytc @danieldimitWhat I should do?

**Comment by sjtuytc** [comment]
I cannot be able to help you debug if you do not provide more informations. As for training YOLO, you may go to the official repo and raise an issue there. Or there probably has been one issue similar with yours.

**Comment by helloyuning** [comment]
> As far as I know the @sjtuytc has just copied the code of YOLOv3. So to build it just follow the instructions from here [darknet](https://github.com/AlexeyAB/darknet). Then to train it follow the instructions also from [darknet](https://github.com/AlexeyAB/darknet). It is well documented. The problem is I did the thing I just described for the Ape object, but YOLOv3 didn't detect anything, so I guess I've done something wrong. Also the training takes very long time 6000 Iterations took ~60 hours of training.
> 
> @sjtuytc do you have any suggestions what I could have done wrong? And could you provide the weights that you've got for the LINEMODE dataset objects?

Hello,
I trying to run this code too, but I got a error when do the step 2(kps annatation).
In sixd.py I found he load sixd data from ‘gt.yml’, id, pose, obj_bb.
It returns a error, no items named obj_bb in gt.yml, I confirm gt.yml, it do not exist.

Could you give me some suggestions?

thanks
yuning

**Comment by sjtuytc** [comment]
It's been a long time and I don't remember these details. Sorry about that.

**Comment by helloyuning** [comment]
Dod you still having dataset of betapose(even part of that, like some yml files)?Anyway, thanks for your reply Best regards 发件人: Zelin Zhao发送时间: 2023년 2월 11일 토요일 오후 2:57收件人: sjtuytc/betapose抄送: helloyuning; Comment主题: Re: [sjtuytc/betapose] How to prepare data as AlexeyAB/darknet's instructions? (#4) It's been a long time and I don't remember these details. Sorry about that.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
